### ISSUE TITLE
ambiguity warnings with DataArrays

### ISSUE THREAD

**Issue by mlubin** [JuliaLinearAlgebra/WoodburyMatrices.jl#15] opened 2016-09-16 09:40 UTC
This appears when `using Gadfly`:

```
WARNING: New definition 
    +(AbstractArray, DataArrays.DataArray) at /home/mlubin/.julia/v0.4/DataArrays/src/operators.jl:276
is ambiguous with: 
    +(WoodburyMatrices.SymWoodbury, AbstractArray{T<:Any, 2}) at /home/mlubin/.julia/v0.4/WoodburyMatrices/src/SymWoodburyMatrices.jl:107.
To fix, define 
    +(WoodburyMatrices.SymWoodbury, DataArrays.DataArray{T<:Any, 2})
before the new definition.
WARNING: New definition 
    +(AbstractArray, DataArrays.AbstractDataArray) at /home/mlubin/.julia/v0.4/DataArrays/src/operators.jl:300
is ambiguous with: 
    +(WoodburyMatrices.SymWoodbury, AbstractArray{T<:Any, 2}) at /home/mlubin/.julia/v0.4/WoodburyMatrices/src/SymWoodburyMatrices.jl:107.
To fix, define 
    +(WoodburyMatrices.SymWoodbury, DataArrays.AbstractDataArray{T<:Any, 2})
before the new definition.
```

I'm using DataArrays 0.3.8 and WoodburyMatrices 0.2.0.

**Comment by timholy** [comment] 2016-09-16 10:13
Duplicate of #13

**Comment by mlubin** [comment] 2016-09-16 10:47
Oops, didn't look through the closed issues. So is this wontfix on 0.4?

**Comment by timholy** [comment] 2016-09-16 11:05
I'd say it's up to @gabgoh. (Or if anyone decides to submit a PR to change it.)

**Comment by timholy** [comment] 2018-07-02 00:45
Not a major issue with the change in ambiguity printing.

**Closed as completed by timholy** 2018-07-02 00:45 UTC
